### ISSUE TITLE
std_not_bencoded_file - any way around this?

### ISSUE THREAD

**Issue by slrslr** [xiaomlove/nexusphp#25]
Hello,
i am using older version of the Nexus script. And some torrent file upload results in:
std_not_bencoded_file

takeupload.php:
```
require_once("include/benc.php");
$dict = bdec_file($tmpname, $max_torrent_size);
if (!isset($dict))
bark($lang_takeupload['std_not_bencoded_file']);
```

You have made some modifications to the bencode since the old script i am using:
https://github.com/xiaomlove/nexusphp/commit/5c4c2ccf8f58138c6449feaa778a0e10f09d0b2a#diff-b977b464c341a216346db9bcb81f524681989d30ee21ab46dd65e2669fdaea25

i have tried to merge these changes various ways but there is empty white screen.

Does it mean that there is no way to process this .torrent file for Nexus script purposes? Have to tell user to re-create torrent using different Bittorrent client?

**Comment by xiaomlove** [comment]
Does this happen to every torrent file or is it an individual torrent file that has this error.

**Comment by slrslr** [comment]
It is NOT all files, but individual - happens from time to time for some files and when it happen, trying to create torrent for same files again results in that error. I have noticed that the torrent that fails currently for me is like 7 years old, [here is](https://drive.proton.me/urls/JG9SXZWHYG#QFpQEmj6eH37) the sample "std_not_bencoded_file" torrent...

**Comment by Rhilip** [comment]
When your $max_torrent_size is very small, then $dict may null (or you can say not set in php).
since `bdec_file` use fopen+fread to get content from file, so the bdec may fail and return null.

- If you want to debug this error, I think you can print those var: `$tmpname, $max_torrent_size, $dict`
- If you want to merge the change of bencode, you can forward to https://github.com/Rhilip/NexusPHP/pull/1 , the commit https://github.com/xiaomlove/nexusphp/commit/5c4c2ccf8f58138c6449feaa778a0e10f09d0b2a is mainly based on this pr. Also Don't forget to use composer.

**Comment by slrslr** [comment]
Thank You, i appreciate your suggestions.

>     * If you want to merge the change of bencode, you can forward to

this seems to be quite hard to merge by manually editing my files and i have no experience in git to merge somehow via CLI. If i know that, maybe i could clone this repo (i know how) then replace 9 files changed in yours mentioned commit by my old files and then do some git command (i do not know parameters) to let git modify my old files based on that particular commit.

My max_torrent_size is 3MB (3145728) 

> print those var: $tmpname, $max_torrent_size, $dict

so i have this in takeupload.php:
```
$dict = bdec_file($tmpname, $max_torrent_size);
echo "<center>tmpname: $tmpname, max_torrent_size: $max_torrent_size,dict: $dict</center>";
```
result is that on torrent upload i see std_not_bencoded_file and: 
```tmpname: /tmp/phpl2dPUd, max_torrent_size: 3145728,dict: ```

file /tmp/phpl2dPUd does not exist when i have checked it
3145728 should be 3MB and the std_not_bencoded_file .torrent is just 18kB

After increasing max_torrent_size to 300MB result is the same not benc. file (happens only for minority of files, like the sample one i have linked earlier).

**Comment by Rhilip** [comment]
Oh, After I download your test torrent file, I find the real reason: 
The old `benc.php` from NexusPHP don't support the **negative number**

When decode the numer, the benc from NexusPHP use regex like `/^i(\d+)e/`, 
so it only support positive integer.
https://github.com/xiaomlove/nexusphp/blob/19d7e048df1450c1afda1aa771a943c12529a971/include/benc.php#L63-L71

However value like `-13` `13` is vaild and only value like ` `,`-0`, `013`, `-013`, `2.127`, `six` are illegal.
And since your std_not_bencoded_file .torrent includes negative number in `$dict['info']['file-media'][2]`
the function `bdec_file` fails and return null when decode this negative number.
![image](https://user-images.githubusercontent.com/13842140/132124119-42f89547-c2a1-4337-a909-c7c91d014507.png)

Change the bencode library to Rhilip/Bencode like the patch which I provided will help you fix this problem. But the most simple patch is edit the `benc.php` file like this.

![image](https://user-images.githubusercontent.com/13842140/132124415-1a0954cb-3536-42e5-877c-d7f2fbb420d7.png)

**Comment by slrslr** [comment]
As instructed, i have opened include/benc.php
replaced line (in my case line 63):
`if (preg_match('/^i(\d+)e/', $s, $m)) {`
by line:
`if (preg_match('/^i(-?\d+)e/', $s, $m)) {`

and line (in my case line 66):
`if ($v === "-0")`
by:
`if (strpos($v, "-0") === 0)`

Linux diff output:
```
$ diff include/benc.php include/benc.php-2021-09-05
63c63
< 	if (preg_match('/^i(-?\d+)e/', $s, $m)) {
---
> 	if (preg_match('/^i(\d+)e/', $s, $m)) {
66c66
< 		if (strpos($v, "-0") === 0)
---
> 		if ($v === "-0")
133c133
< ?>
---
> ?>
\ No newline at end of file
````

yet the std_not_bencoded_file error is returned anyway for the .torrent file i have linked earlier, while using original and modified benc.php file, max_torrent_size is kept very high..

**Comment by Rhilip** [comment]
It seems very stange...
Because after edit the `benc.php` file, I can parse you torrent with corrent `$dict` return.

Maybe you can compare this archive [test.zip](https://github.com/xiaomlove/nexusphp/files/7111778/test.zip) with your local changes. 

My test environment is PHP 8.0, 
Since I only use the function `strpos() === 0` but not `str_starts_with()` (Which is added in PHP 8.0), I think it is compatible with PHP 5.x to PHP 8.0 .

```
PHP 8.0.10 (cli) (built: Aug 25 2021 08:46:03) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.10, Copyright (c) Zend Technologies
```

**Comment by slrslr** [comment]
Thank you @Rhilip.
Maybe i did a typo while copy & pasting or something. Now it is working and uploading, including files that previously failed. It seems to extracts all needed attributes of the bencoded file and download works too.
Thank you very much for your help and users will apparently be able to upload all torrents now. 😍

**Comment by slrslr** [comment]
Hello @Rhilip I am returning after 2 years. I have noticed that for some (like maybe up to 5%) of the torrent files uploaded by the [original Nexus script](https://github.com/burpheart/NexusPHP_safe) the torrent tracker announce inside bittorrent client is returning "unexpected end of file in bencoded string".
It also happen when i try to edit .torrent using http://torrenteditor.com and upload it to a tracker. From my testing, i believe that the Nexus is repeatedly saving malformed torrent file in this particular case and when contacted by peer, it maybe checks the torrent it has and discovers the "unexpected end of file".
Would you be willing to take a look on this torrent? If so, which files I should supply to you please?
There already is:
https://github.com/burpheart/NexusPHP_safe/blob/master/include/benc.php
And there is input and output .torrent file: https://drive.proton.me/urls/F1EBDK9P4G#NqlHx9nS84EJ
Possibly related files (i am not using these, are from a newer script I am not using): https://github.com/xiaomlove/nexusphp/commit/5c4c2ccf8f58138c6449feaa778a0e10f09d0b2a

**Comment by xiaomlove** [comment]
you can test on my demo site by yourself. it's open register

**Comment by slrslr** [comment]
@xiaomlove  > you can test on my demo site by yourself. it's open register
I am unsure if i can. You would need to approve all recent torrent to prevent announce error in BT clients "torrent review not approved"? I wish you publish your contact on your profile (as u can see on [mine](https://github.com/slrslr)) or website, so this can be talked in private.

**Comment by xiaomlove** [comment]
you can contact me on telegram

**Comment by slrslr** [comment]
> you can contact me on telegram

@xiaomlove  Telegram does not send me a verification SMS. Can you link me to other contact or [use my contact](https://paste.nolog.cz/?edeb105b53c6a54e#C4cNnqUYaLZUFALqeZHPMBKCf8wFbtmw8teok69cdY4B) (password: x)? I would be interested to hire you to fix this or if interested, even to implement other features.

**Comment by xiaomlove** [comment]
@slrslr please view the [composer.json](https://github.com/xiaomlove/nexusphp/blob/php8/composer.json) file. Or view blog about page.

**Comment by slrslr** [comment]
Since qBittorrent 5.0.0 i can no longer see this warning/error.
v. 5.0.0 on my PC is using Qt: 6.7.3. Libtorrent: 2.0.11.0, Boost: 1.86.0, OpenSSL: 3.3.2, zlib: 1.2.13

@xiaomlove  It would be good if you would publish your contact on your profile (as u can see on [mine](https://github.com/slrslr)) or website. Thank you anyway.
