### ISSUE TITLE
[REQUEST] Torrent Approval

### ISSUE THREAD

**Issue by ghost** [xiaomlove/nexusphp#74]
Hello xiaomlove, how are you?
I would like to request the option to remove the "offers" and switch to moderation, that is, all torrents are posted directly and pending approval from a moderator+

Thanks, Turko

**Comment by xiaomlove** [comment]
Will consider adding a review mechanism

**Comment by xiaomlove** [comment]
1.7.16 Added the approval function, the default state of torrent release is unaudited, the front-end users can see and download. If you find that it is not qualified, you can click the approval button to change the approval status to rejected, so that only users with permission can see it in the torrent list (including the case of dead torrents).

**Comment by Stargaterom** [comment]
hello xiaomlove, thank you very much for your development on nexus, at the approved level the torrent would it be possible to block the user downloaded the .torrent if the torrent was not accepted by a Staff member
 because the current function does not allow to be able to do the pending properly .

here are 2 examples that could be nice on nexus thanks again for your work!!!

1)
when torrents and none on the pending users will not be able to download the .torrent file it will have to be approved by a member of staff from (Staff member).

2)
or make torrents not yet accepted or validate that it is not visible for users of class lower than (Staff member)

**Comment by xiaomlove** [comment]
It is currently designed this way for the following reasons.
**For most sites, there is not much effort to review. Therefore, the default state is unvetted, which is actually no different from the vetted state, and users can download the torrent normally**. When the administrator sees the obvious non-conformity, the review status will be changed to denied, and the torrents will be restricted at this time.

**Comment by ghost** [comment]
@Stargaterom idea 2 pleases me and would be very useful. Better to have more work to review than to lose torrent quality.

I believe it could have an option to be moderated/approved or the way it is today. It would be a very complete system.

**Comment by Stargaterom** [comment]
@xiaomlove @TurkoSeed  hello, xiamlove thank you very much for answering yes indeed you are working on a development idea, I do not question your way of seeing things!! , I was only proposing a feature which and on many sites currently (torrenttrader, gazelle) etc ... to be able to control the torrents before which are visible to the members, we have a team of pending staff members who are currently struggling to control all uploads of the day and some torrent passes through !! , as turkoseed expressed, it avoids having full torrents that do not correspond with the rules put in place by the staff. I hope you will understand and that you will not take it badly because you are doing a great job in development, I remain at your disposal if you wish to improve this system for efficient pending or add this option on the staff panel for those who would like to use this functionality on nexus thank you very much friends.

**Comment by xiaomlove** [comment]
@Stargaterom @TurkoSeed It is possible to give a configuration item whether unvetted torrents are visible to normal users. The default is visible, which remains unchanged from the current state. If I change this configuration item to invisible, only torrents that have been approved will appear in the torrent list, and the approval status icon will be forced to be displayed for managers.

**Comment by ghost** [comment]
@xiaomlove It would be nice, as long as in the update set all current torrents are approved and the change is from now on. I think this would make nexusphp pretty complete.

**Comment by Stargaterom** [comment]
hello @xiaomlove , if I understood correctly on the torrent list you can add invisible option for the lower class to the staff if they are not approved in the approval panel it would be really good!! , thank you very much for taking the time to read and respond to our requests xiaomlove .

@xiaomlove @TurkoSeed yes indeed as would say turkoseed it would be necessary to have an option to approve all the torrent for which we already have a torrent base already in place then effectively by the site to continue the pending for the new addition.

**Comment by xiaomlove** [comment]
You can upgrade to the latest commit to test this function，before change configuration [Torrent settings]->[Visibility of not reviewed torrents] to 'no', change old torrents's approval_status = 1: 
```
update torrents set approval_status = 1;
```

**Comment by Stargaterom** [comment]
@xiaomlove thank you very much for info for approved all torrents through a bdd, just have a question, I have a problem with imdb info which is purged every 7 days I want to keep everything you knew how to do because otherwise we have nothing left in the bubble by passing the mouse over the title of the torrent and we and oblige to update info imdb of the torrent thank you for your answer cordially

**Comment by Stargaterom** [comment]
Hello @xiaomlove , it would be possible to have a notification displayed at the top to find out if there are new torrents waiting to be approved, such as for staff messages or pm messages where we have a colored frame to let us know. thank you in advance.

example picture:
https://prnt.sc/b11WOyhcCi7o

**Comment by xiaomlove** [comment]
> Hello @xiaomlove , it would be possible to have a notification displayed at the top to find out if there are new torrents waiting to be approved, such as for staff messages or pm messages where we have a colored frame to let us know. thank you in advance.
> 
> example picture: https://prnt.sc/b11WOyhcCi7o

It is possible to have

**Comment by Stargaterom** [comment]
> > Hello @xiaomlove , it would be possible to have a notification displayed at the top to find out if there are new torrents waiting to be approved, such as for staff messages or pm messages where we have a colored frame to let us know. thank you in advance.
> > example picture: https://prnt.sc/b11WOyhcCi7o
> 
> It is possible to have

haaa @xiaomlove really great if you can add thank you very much

**Comment by xiaomlove** [comment]
@Stargaterom 1.7.17 added.

**Comment by Stargaterom** [comment]
Thanks a lot @xiaomlove
