### ISSUE TITLE
[Request] Set the time of the automatic purge of IMDB information

### ISSUE THREAD

**Issue by Skyline-007** [xiaomlove/nexusphp#81]
Hello

I would like to know how to adjust the time of the automatic purge of IMDB information ?

(Example: the automatic purge of IMDB information is done after 7 days, I would like to pass it to 30 days)

Or how to disable automatic purge of IMDB information ?
(To constantly keep all IMDB information on all posts)

Thank you in advance for your answer

Best regards

Skyline-007

**Comment by xiaomlove** [comment]
Currently imdb information does not expire after it is obtained manually

**Comment by Stargaterom** [comment]
hello @xiaomlove , 
when did you change this condition because I am progressing your work and on several tests my imdb information is purged every 7 days, what and the file that will prevent this purge thank you cordially

ps: because I have the same problem currently on version 1.7.17

**Comment by xiaomlove** [comment]
ok, i will take a look

**Comment by Stargaterom** [comment]
thank you @xiaomlove

**Comment by xiaomlove** [comment]
Currently it is not clear where to delete, 1.7.18 there are changes to the possible places, you can update to see

**Comment by Stargaterom** [comment]
hello, @xiaomlove I applied your change: /nexus/Imdb/Imdb.php
==================================================================================
so :
      if (!is_file($mainCacheFile)) {
            do_log("mainCacheFile: $mainCacheFile not exists, return");
            return true;
        }
==================================================================================

unfortunately the problem and always present every 7 days info bubble and the rating of the film disappears.

The imdb information on the detail of the torrent remains to be displayed well, therefore the concern is its bubble information when you pass the mouse over the title.

I want to restart the test on a file to see if it still withdraws on its own.

I'm really sorry to bother you, my truth is that it can be annoying to have to regenerate the bubbles every 7 days.

Thank you in advance for all your updates and the time you spend for us.

**Comment by xiaomlove** [comment]
Waiting for your results, at the moment I can't think where imdb information would be deleted

**Comment by Stargaterom** [comment]
Hello friends @xiaomlove  ,

here are screenshots of the test, 

bubble info and cover + rating on the torrent page = https://prnt.sc/Lh9__jCbtx3J 
imdb info on prez  = https://prnt.sc/NzbcH-X5BAUX

you can see the date when imdb was updated on the prez and what it gives on the torrent page with the bubble linking to this torrent

 in 7 days I'll take a screenshot to show you what it's done.

on my side, I also looked for and did several tests in the imdb conf files in nexus and in the vendor and the info is purged all the same all by itself within a delay of 7 days its really annoying I hope stupid will find an alternative to itself problem

cordially thank you

**Comment by Skyline-007** [comment]
Hello

Alright thank you for your response.

Hope you find a solution in the future

I tried different tests on my side for IMDB (/imdb/imdb.class.php and imdb/imdb_config.php) but nothing to do it always purges IMDB information.

Have a good day

Skyline-007

**Comment by Stargaterom** [comment]
Hello friends @xiaomlove ,
I look at all the files and compare concerning imdb.
my official version to use for my community currently = I'm on 1.6 beta 12

I also work in parallel on the updates of your auto-update version
my tests on version 1.6 beta 12 and 1.7.18 for imdb

on version 1.6 beta 12 and 1.7.18 the sound files are identical.

at the root imdb folder its identical
in nexus/imdb its identical too
I even replaced imdbphp in the vendor at the root with that of version 1.7.17 provided on nexusphp.org for 1.6 beta 12 which allowed me to solve the problem of cover and plot-outline

I also added what you told me = Create background task (crontab)

I have
unfortunately my imdb information which is purged in 7 days on the 1.6 beta 12 for the 1.7.18 my test and still in progress

you wonder why we and on the 1.6 beta 12
we started at this time my my knowledge was very limited and therefore as I did not want to put the engine out of order I did not do the migrations my follow-up to this you had changed the ad to an api
and many changes in the database which would all be a mess to do.

moreover we will be obliged to have to recover all the .torrent 1 by 1 to put them back in seed because the keys are not the same.

so I'm working on 2 versions to follow the improvements you've made and add something that would be compatible with 1.6 beta 12.

so I think its off topic if you can help with the migration of torrent data without the need for all members to be forced to seed all their torrents because announcement and key and more.

I thank you in advance for all that you do your engine has great potential.

**Comment by Stargaterom** [comment]
hello @xiaomlove well here is my result actually for the version followed in auto update so we and at 1.7.20 the imdb info is automatically regenerated after 7 days so no longer have to do it manually,

do you have a little trick so that I can integrate this function into my version 1.6 beta 12 because I don't know what you have to add or modify so that the imdb is automatically renewed on new ones
version

**Comment by Stargaterom** [comment]
hello @xiaomlove , I have examined the logs and indeed in the 1.6 beta 12 it purges info cache imdb here are my lines in tmp/nexux log.

local.info /xxxx/xxxx/xxxx/nexus/Imdb/Imdb.php:111 Nexus\Imdb\Imdb->purgeSingle unlink: /xxxx/xxxx/xxxx/imdb/cache/title.tt13784584
local.info /xxxx/xxxx/xxxx/nexus/Imdb/Imdb.php:111 Nexus\Imdb\Imdb->purgeSingle unlink: /xxxx/xxxx/xxxx/imdb/cache/title.tt13784584.fullcredits
local.info /xxxx/xxxx/xxxx/nexus/Imdb/Imdb.php:111 Nexus\Imdb\Imdb->purgeSingle unlink: /xxxx/xxxx/xxxx/imdb/cache/title.tt13784584.releaseinfo
local.info /xxxx/xxxx/xxxx/nexus/Imdb/Imdb.php:111 Nexus\Imdb\Imdb->purgeSingle unlink: /xxxx/xxxx/xxxx/imdb/cache/title.tt13784584.technical

can you do something to prevent this purge, thank you in advance
because I despair of days of research and testing and I can't find what does this!!!

if I understood correctly your new version on more centering on the ptgen, my is which touches has imdb I have identified: imdb.php, imdb_conf, imdb. class , retriver.php

I tried to compare the files between the 2 versions which changes my its not easy because if you change the structure the code will not be where it is so I have tried all and come to nothing conclusive currently sniff

**Comment by xiaomlove** [comment]
The only place where purgeSingle() is used is when [updating imdb data](https://github.com/xiaomlove/nexusphp/blob/php8/public/retriver.php#L32), where it is deleted first and then updated, what would be the problem?

**Comment by Stargaterom** [comment]
hello @xiaomlove the problem and that on 1.6 beta 12 its imdb is purged but does not update automatically like version 1.7.19, you have to redo everything manually as if you had just added new information in the library .

when the info is purged I have to redo the following manipulation on all the imdb info of the posts which are 7 days old as in the capture below!!

https://prnt.sc/-o2NzJ9IBEgR

**Comment by xiaomlove** [comment]
the point is that we do not know where the problem is, do you know?

**Comment by Stargaterom** [comment]
unfortunately I is not the solution to this problem version 1.7.19 the information is automatically regenerated after 7 days but on your version 1.6 beta 12 imdb is purged and it does not regenerate automatically I its not really what has been improved in the new version which manages this function which avoids losing all the information

only you could help because you developed the engine

**Comment by Stargaterom** [comment]
what is the difference between 1.6 beta 12 and 1.7.19 in terms of imdb info thats the real question is there a condition in the cleanup in 1.7.19 which and not in 1.6 beta 12 ?

**Comment by Stargaterom** [comment]
or if not, since my info is not automatically updated, can you prevent the purge directly? 

by modifying the updating imdb data file ?

**Comment by Stargaterom** [comment]
basically it's related to update/edit get desc which was added in 1.7.2 as i understand i have to try to add its changes in my 1.6 beta 12 but i don't really know who and the link for update/edit get desc because this update has several addition text alignment tag + update/edit get desc + improved note

**Comment by Stargaterom** [comment]
well i tried some changes related to updating imdb data the problem with 1.7.2 there were alot of changes and so my 1.6 beta 12 got into error as soon as i changed function.php so i dont don't know what to do for the fix, the only solution would be to update to a recent version but I'll have to start all over again because users won't be compatible and neither will torrents due to the change in the API announcement which would be very annoying as we migrated to nexusphp and i started over 4 months ago and i don't have the strength to start all over again.

the only solution would be to block imdb information from being purged and keep all the information even if it is no longer used and for that i need someone with coding skills to help me edit the right files to from links when purging

**Comment by Stargaterom** [comment]
good view that I have not found the solution for my version 1.6 beta 12 about imdb which is purged and which is not automatically updated every 7 days compared to the last stable version that imdb is automatically regenerated I will abandon my search on this version and continue to develop the current one
